spring:
  application:
    name: taskManageSys-regAndLoginWeb
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/acm
      username: root
      password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
      host: smtp.163.com
      port: 465
      username: acm1633@163.com
      password: TTZXDKGUSAWWLXMD
      properties:
        from: acm1633@163.com
        mail:
          smtp:
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
  redis:
        database: 0
        host: localhost
        port: 6379

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.acm.front
  consumer:
    check: false
    timeout: 50000
    retries: 0

server:
  port: 8000
  servlet:
    context-path:
    encoding:
      charset: utf-8
      enabled: true
      force: true

