spring:
  application:
    name: taskManageSys-dataservice
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/acm
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.acm.dataservice.service
  provider:
    timeout: 50000
    retries: 0
